apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: stock-mldl
  labels:
    app: api-gateway
    app.kubernetes.io/part-of: stock-mldl
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 80
      targetPort: 8000
