apiVersion: v1
kind: Service
metadata:
  name: crawler-service
  namespace: stock-mldl
  labels:
    app: crawler-service
    app.kubernetes.io/part-of: stock-mldl
spec:
  type: ClusterIP
  selector:
    app: crawler-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
